/**
 * Express.js x402 Integration Example
 * Demonstrates automatic receipt creation with Express middleware
 *
 * Uses @solana/web3.js v1 for Anchor compatibility
 */

import express, { Request, Response, NextFunction } from 'express'
import { Program, AnchorProvider, Wallet, BN, type Idl } from '@coral-xyz/anchor'
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
} from '@solana/web3.js'
import { createHash } from 'crypto'
import * as fs from 'fs'

// Extend Express Request to include x402 payment data
interface X402Request extends Request {
  x402Payment?: {
    payer: string
    amount: BN
    receiptPda: string
  }
}

// Content type enum (mirrors on-chain ContentType)
const ContentType = {
  Chat: { chat: {} },
  Audio: { audio: {} },
  Video: { video: {} },
  Image: { image: {} },
  Data: { data: {} },
  Compute: { compute: {} },
  Other: { other: {} },
} as const

// Load program IDL (generated by anchor build)
const idl = JSON.parse(
  fs.readFileSync('./target/idl/vote_registry.json', 'utf-8')
) as Idl

// Load seller keypair (recipient of x402 payments)
function loadSellerKeypair(): Keypair {
  const secretKey = Uint8Array.from(
    JSON.parse(fs.readFileSync('./seller-keypair.json', 'utf-8'))
  )
  return Keypair.fromSecretKey(secretKey)
}

// Solana RPC URL
const SOLANA_RPC_URL = process.env.SOLANA_RPC_URL || 'https://api.devnet.solana.com'

// Program ID
const PROGRAM_ID = new PublicKey(
  process.env.VOTE_REGISTRY_PROGRAM_ID || '6yqgRTrKwgdK73EHfw8oXaQvhDqyzbjQKS5pDUncMZrN'
)

// x402 middleware configuration
interface X402MiddlewareConfig {
  program: Program<Idl>
  provider: AnchorProvider
  sellerKeypair: Keypair
  contentType: typeof ContentType[keyof typeof ContentType]
  onReceiptCreated?: (receiptPda: string, txData: { payer: string; amount: BN; signature: string }) => void
  onError?: (error: Error, req: Request) => void
}

// Simple x402 middleware
function x402Middleware(config: X402MiddlewareConfig) {
  return async (req: X402Request, res: Response, next: NextFunction) => {
    const xPayment = req.headers['x-payment'] as string | undefined

    if (!xPayment) {
      res.status(402).json({
        error: 'Payment Required',
        message: 'Missing X-PAYMENT header',
      })
      return
    }

    try {
      // Parse x402 payment payload
      const payloadJson = Buffer.from(xPayment, 'base64').toString('utf-8')
      const payload = JSON.parse(payloadJson)

      if (payload.scheme !== 'exact' || payload.payload?.chain !== 'solana') {
        res.status(400).json({ error: 'Invalid payment scheme' })
        return
      }

      // Extract transaction details (simplified for example)
      const signature = `mock_sig_${Date.now()}` // In production, extract from tx
      const signatureHash = Array.from(
        createHash('sha256').update(signature).digest()
      )
      const amount = new BN(100_000) // In production, parse from tx

      // Derive receipt PDA
      const payer = Keypair.generate().publicKey // In production, parse from tx
      const [receiptPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from('tx_receipt'),
          payer.toBuffer(),
          config.sellerKeypair.publicKey.toBuffer(),
          Buffer.from(signatureHash),
        ],
        PROGRAM_ID
      )

      // Create receipt on-chain
      await config.program.methods
        .createTransactionReceipt(
          signature,
          signatureHash,
          amount,
          config.contentType
        )
        .accounts({
          receipt: receiptPda,
          payerPubkey: payer,
          recipientPubkey: config.sellerKeypair.publicKey,
          creator: config.sellerKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([config.sellerKeypair])
        .rpc()

      // Attach payment info to request
      req.x402Payment = {
        payer: payer.toBase58(),
        amount,
        receiptPda: receiptPda.toBase58(),
      }

      // Callback
      config.onReceiptCreated?.(receiptPda.toBase58(), {
        payer: payer.toBase58(),
        amount,
        signature,
      })

      next()
    } catch (error) {
      config.onError?.(error as Error, req)
      res.status(400).json({
        error: 'Payment verification failed',
        message: (error as Error).message,
      })
    }
  }
}

async function main() {
  // Setup Solana connection
  const connection = new Connection(SOLANA_RPC_URL, 'confirmed')

  // Load seller keypair
  const sellerKeypair = loadSellerKeypair()

  // Create wallet and provider for Anchor
  const wallet = new Wallet(sellerKeypair)
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
  })

  // Initialize vote registry program
  const program = new Program(idl, provider)

  // Configure x402 middleware
  const x402Config: X402MiddlewareConfig = {
    program,
    provider,
    sellerKeypair,
    contentType: ContentType.Chat,

    onReceiptCreated: (receiptPda, txData) => {
      console.log('Receipt created:', {
        receiptPda,
        payer: txData.payer,
        amount: txData.amount.toString(),
        signature: txData.signature,
      })
    },

    onError: (error) => {
      console.error('x402 middleware error:', error.message)
    },
  }

  // Create Express app
  const app = express()
  app.use(express.json())

  // Public endpoint (no payment required)
  app.get('/api/public', (_req: Request, res: Response) => {
    res.json({
      message: 'This is a public endpoint',
      service: 'GhostSpeak AI Agent',
    })
  })

  // Protected endpoint (requires x402 payment)
  app.post(
    '/api/chat',
    x402Middleware(x402Config),
    async (req: X402Request, res: Response) => {
      const { payer, amount, receiptPda } = req.x402Payment!

      console.log('Serving paid request:', {
        payer,
        amount: amount.toString(),
        receiptPda,
      })

      // Your AI agent logic here
      const response = await processAIRequest(req.body.prompt)

      res.json({
        response,
        payment: {
          payer,
          amount: amount.toString(),
          receiptPda,
          message: 'You can now vote on this interaction using the receipt PDA',
        },
      })
    }
  )

  // Example AI processing function
  async function processAIRequest(prompt: string): Promise<string> {
    return `Response to: ${prompt}`
  }

  // Start server
  const PORT = process.env.PORT || 3000
  app.listen(PORT, () => {
    console.log(`x402-enabled server running on port ${PORT}`)
    console.log(`Seller address: ${sellerKeypair.publicKey.toBase58()}`)
    console.log(`Program ID: ${PROGRAM_ID.toBase58()}`)
    console.log('\nProtected endpoints:')
    console.log(`  POST /api/chat - Requires x402 payment`)
  })
}

main().catch(console.error)
